name: Deployment-pipeline

on: 
 push:

jobs:

   build:

    runs-on: ubuntu-latest

    steps:
     - name: Print-Command-Execute
       run:  echo "Hello Adil"
     
     - name: Print-Learning-GitHub-Actions
       run:  echo "Learning GitHub Actions"

     - name: Print-Date
       run:  echo date