name: Deployment-pipeline

on: 
 push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Print-Building-Project-Command
      run:  echo "Building Project..."
    
  test:
     runs-on: ubuntu-latest

     steps:
     - name: Print-Testing-Project-Command
       run:  echo "Testing Project..."

  deploy:
      runs-on: ubuntu-latest

      steps:     
       
       - name: Print-Deploy-Project-Command
         run:  echo "Deploying Project..."