name: Deployment-pipeline

on: 
 push:

jobs:

   build:

    runs-on: ubuntu-latest

    steps:

     - uses: actions/checkout@v4
     - name: Print-Welcome-Command
       run:  echo "Welcome"
     
     - name: Print-Current-Directory
       run:  pwd

     - name: Print-List-Files
       run:  ls

     - name: Print-Finish-Command
       run:  echo "Finish"